### ISSUE TITLE
007 is Too Thick

### ISSUE THREAD

**Issue by johnnyxmas** [Xyl2k/TSA-Travel-Sentry-master-keys#15]
While you can certainly cram it in there with some fiddling at the current 2.0mm, the actual key width for 007 is 1.6mm. 

![img_0074](https://cloud.githubusercontent.com/assets/6288329/10055862/1382f08c-61fe-11e5-9fd7-0ae2c6000b2e.JPG)

**Comment by johnnyxmas** [comment]
I've had great success with my two 007 locks using the new thinner 007 key in my fork. Submitted a pull request for now, but waiting for more testers. 

https://github.com/johnnyxmas/TSA-Travel-Sentry-master-keys/blob/master/TSA007_stubby.stl

![img_0075](https://cloud.githubusercontent.com/assets/6288329/10055901/5708bfb2-61fe-11e5-9d6f-f0b2be8eb783.JPG)

**Comment by MS3FGX** [comment]
Your key's are coming out at 2 mm? The STL specifies 1.75, and when they come off my printer I am measuring ~1.71 mm on my calipers.

Maybe you're running into some kind of layer height problem? Are you using .3 mm layers perhaps?

**Comment by Xyl2k** [comment]
The actual TSA007 file from the main branch work absolutely fine here.

![2015-09-23_22-53-22](https://cloud.githubusercontent.com/assets/8536299/10058523/2a911f68-6246-11e5-9bd1-730fca71a2a5.jpg)

**Comment by johnnyxmas** [comment]
I just pulled the file off this repo and confirmed in 2 different programs. 2.01mm. Also, I'm printing at .01mm layer height for accuracy. Resulting prints are within .05mm of the STL, sometimes even less. 

<img width="933" alt="screen shot 2015-09-23 at 4 27 38 pm" src="https://cloud.githubusercontent.com/assets/6288329/10059706/30643fa8-6212-11e5-8c94-07e90e7a9575.png">

<img width="623" alt="screen shot 2015-09-23 at 4 27 20 pm" src="https://cloud.githubusercontent.com/assets/6288329/10059717/4412aa9e-6212-11e5-8f90-b48f7c5a6269.png">

**Comment by johnnyxmas** [comment]
1.75 should have enough room to work, but 2.0 definitely doesn't easily fit in my locks. They're completely different from Xyl2k's; his are combination locks, mine are not. 2.0mm is standard for Schlage or Kwikset-style "house" keys, so I'd believe if some of these keys need to be that width, but the keys for my 007 are definitely thinner, measuring ~1.6mm.  Perhaps there's a slight difference in the keyway width between the two. A slightly thinner key should work on both, but the thicker one would not. 

I can try them at 1.75 later today and if that works in my lock, I'd say at least replace the current 2.0's with that.

**Comment by MS3FGX** [comment]
Well yeah, the entire key itself is 2 mm high, but that's because the "handle" is thicker than the actual key. At least on my stubby ones anyway, the original keys are the same thickness throughout.

If you pull the regular TSA007, you should see it reads as 1.75 mm.

**Comment by johnnyxmas** [comment]
Confirmed; good call; I confirmed this at the shoulder. Either way, the 1.75's take a lot of struggling to get into these locks. Once you get it in a few times and wear \ compress the plastic down, the key does work.  Can you try my 1.6's in the combination-style lock and see if they still work? If so, this may be a better master key. If it's too thin to the point where it's difficult to use there, we may need to either declare my old locks "obsolete,"  create a "7b" key for them,  or just make a note that the keyways on some of them are a bit thinner and require some force (probably the easiest option). I'd have been willing to write it off as poor lock production tolerances, but I've got 2 of them here.  :/

**Comment by Xyl2k** [comment]
Your version worked too but seem very fragile due to the tickness

![2015-09-24_00-24-21](https://cloud.githubusercontent.com/assets/8536299/10060648/a04bbc52-6252-11e5-913b-4df060479f86.jpg)

**Comment by MS3FGX** [comment]
That would be my concern, surely the thinner one would work on both locks, but why make the default smaller and weaker?

This might be something where we have a note in the docs that says some makes/models/types/whatever of locks need Z scalled down slightly.

**Comment by johnnyxmas** [comment]
I'm OK with that. I was thinking of adding some basic / universal printing tips to the README per some conversations with darksim, anyway. This is certainly something that could potentially apply to all keys.
