### ISSUE TITLE
Key Dimension are to small

### ISSUE THREAD

**Issue by morawekj** [Xyl2k/TSA-Travel-Sentry-master-keys#5]
I just print your TSA002 Key, and they are too small, TSA002 is JMA LAS2 or Silca LS13R Key Blank,
Your 14mm lenght is in original about 22mm

http://www.aldridgesecurity.co.uk/p-3699-silca-ls13r-to-suit-las.aspx

**Comment by Xyl2k** [comment]
thanks for the feedback, yeah all keys are not yet good, the TSA006 is a bit tricky too as i don't know what it looks like from the other side.
If you have access to TSA002 (or any other keys) can you scan it ?
it would be the best way to get the profile of the key. It avoids parallax and lens errors from photography

**Comment by johnnyxmas** [comment]
I suspect they're all too small by the same amount. See attached images for helpful dimensions for an 007 I have. Looks like 14mm from tip to shoulder, and the shoulder width is 7mm.   This means they need to be 57.142% larger, however the z-height would need to remain static. This can potentially be done during slicing; I will have to try tomorrow. Either way, the proper way to fix this is to correct it in the original designs, not while slicing. 

![img_0017](https://cloud.githubusercontent.com/assets/6288329/9807116/219715c0-5814-11e5-87c5-3c0ad20255e8.JPG)

![img_0020](https://cloud.githubusercontent.com/assets/6288329/9807117/2197d5fa-5814-11e5-9d74-b2d09051e936.JPG)

**Comment by johnnyxmas** [comment]
Regarding 006: yes, it's useless without seeing the other side. Not a massive concern, as this lock seems to be very rare.

**Comment by johnnyxmas** [comment]
CONFIRMED. An increase of X & Y of 57% while maintaining Z DOES WORK. 
![copanohwoaae7wm](https://cloud.githubusercontent.com/assets/6288329/9822405/e4f7a55e-5885-11e5-9982-5aeb8abafcc4.jpg)

**Comment by MS3FGX** [comment]
This is excellent feedback, something which is desperately needed to narrow down what does and doesn't work. 

My only concern is making commits which might work perfectly for one person, and not at all for another. As it stands we have people using the existing STL files and opening locks on the first try, and then we have a case like yours where you needed to scale them up by a fairly large margin. 

To me that means we either don't have a great understanding of how different people's printers/slicers are interpreting such intricate designs, or that the locks themselves are at such poor tolerances that the key only has to be vaguely correct. 

In either event, I'd really like to see an effort to collect data from users as to their printing environment (hardware, slicer, filament, temps, etc) and also the make/model of the locks they are testing against before we start throwing out changes to see what sticks.

It's entirely possible that there won't be a single file that prints properly on all printers and opens all locks. But we should at least try and get as close as possible.

**Comment by johnnyxmas** [comment]
I won't replace the original files; just upload my mods. Working on new STLs right now. AFAIK, we only have a single user who opened a single lock with the original print. Let's not forget that we're dealing with a lot of garbage locks that can be opened pretty easily with a rake / screwdriver / etc. 

Should I just fork to my own repo?

**Comment by exibar** [comment]
I have a 002 lock here tat I've been trying to scale up during slicing to no avail.  I've also tried different slice widths... from .05 to .3 without success.  I'm using PLA at 185 degrees.

**Comment by johnnyxmas** [comment]
Are you using my recommended ratios above?

**Comment by Xyl2k** [comment]
What MS3FGX said.
slicing and 3d printer config is also a vector, i'm gonna buy a couples of TSA locks on ebay and try to see what's going on.
As some people got some keys to work without scaling, it would be probably better to fork a own repo or just renaming to avoid overwriting the original files (unless we are positive and don't need them anymore)

**Comment by johnnyxmas** [comment]
I have a fork. Finishing up the full-sized STLs. Stand by.

**Comment by johnnyxmas** [comment]
Pull request submitted. Have a look, LMK. I understand the size issue is controversial, so I moved everything to separate directories. We can probably close this issue.

**Comment by MS3FGX** [comment]
Printing 007 and 002 now.

**Comment by johnnyxmas** [comment]
Since we're crowdsourcing testers, here's some suggested text for the readme. This is how I got the 007 ratios correct:

### WE NEED TESTERS \ REAL KEY SIZES!
- If you have a TSA-approved lock and key, and the master key does not work, open an "Issue" and provide the following measurements of your lock's key:
  - Blade length from shoulder to tip
  - Shoulder height from top to bottom

**Comment by Xyl2k** [comment]
what's do you think of this form ?
https://docs.google.com/forms/d/1IhyyOiXtnCX5xOOxgDMyarj06O6NzQP8H_6wbRZQrFQ/viewform?c=0&w=1

**Comment by johnnyxmas** [comment]
Great start! However, we need to petition feedback from people who say their keys did not work. Since we're almost definitely dealing exclusively with a sizing issue (i.e. not a bitting or key type issue), then getting an accurate measurement of the key that came with their lock is most helpful. I only need a measurement from tip-to-shoulder, and shoulder height:

https://schlagelocks.files.wordpress.com/2009/01/schlage-lock-diagram4.jpg

Unless you want to just have people open individual bug issues for that.

**Comment by MS3FGX** [comment]
I agree, this is a good idea, but it isn't asking the questions we need answered. 

The biggest question to me is how some people are having success with the original, and others with the enlarged version. I would be very interested in seeing a form that asked:

A. What file you used
B. What printer/slicer you used
C. What are the dimensions of the **printed** key

If we can ascertain what results people are getting in the real world with these files on their individual setups, we could make much more informed moves going forward.

My best theory right now is that some people's printers are incorrectly calibrated and printing the keys too large. That would explain why the original files worked for some people, but when they printed the 157% files the keys ended up too large.

**Comment by jimklo** [comment]
I think the simple solution to this is having documented target dimensions.
We all know that we can't control everyone's calibration, and most of that
is handled per printer. So the easiest approach is to document overall
target sizes; height, width, and thickness; to the nearest 0.01mm. The STL
needs to be the normal, not some combo of printer & STL. Technically all
this is available from the STL - but often the lazy need help with this.

This way when you print version 1 of the key and version 2 - you know what
size they should measure before testing in a lock. Otherwise if the printed
version is smaller/larger than the STL size, any bug/success is more or
less invalid.

A list of good filament materials for printing keys might also be good to
maintain. My guess is PETG and ABS would be good candidates, but ABS
shrinkage might be difficult to test with. But I think printer/filament
specific tips that are relevant to printing keys should be in the GH wiki,
not in the repo.

**Comment by Xyl2k** [comment]
I got some datas per mails but don't know if it's accurate for the moment
001 = 0.1cm
003 = 0.2cm
004 = 0.35cm
005 = 0.15cm
006 = 0.2cm
007 = 0.1cm

i'm gonna update 003 and 006 soon (someone sent me scanned pictures front and back of his keys) as i was missing some part it would be definitely better, although i'm not gonna do it right now. (I'm concentrating on other work at the moment, but this should be quick.)

**Comment by johnnyxmas** [comment]
I still submit that 006 is pointless without having front and back pics of the master.

What are these measurements you posted? Z height? If so, I can confirm 007 is about .75mm too thin.

**Comment by johnnyxmas** [comment]
Now [THIS](https://twitter.com/bernard/status/641662069427847168) is interesting

This lock is WAY smaller than the 007's I have here. The Xyl2x master key is clearly properly-sized for it. This is a big can of worms, but explains the divide. Are there multiple sizes of TSA master keys in the wild?!

**Comment by Xyl2k** [comment]
for 003 and 006 a little birdy sent me scanned picture of them.
i've not yet pulled them but if you want to have a look: http://temari.fr/tsa_revision_v2.rar
even if tsa006 is 'hard' to print at least this one is more accurate i think.

**Comment by johnnyxmas** [comment]
Here is a scan of master keys from IronGeek for 002, 004, 005 & 007 (top to bottom). Good at least for showing proper scale:

![co4vl5fw8aaws-1](https://cloud.githubusercontent.com/assets/6288329/9878513/b59546a8-5b88-11e5-8a88-344154f70be5.jpg)

**Comment by johnnyxmas** [comment]
NOTE: I updated the info above. These are confirmed-functional hand-made master keys.

**Comment by johnnyxmas** [comment]
My enlarged 002 & 003 keys work well enough that Ars Technica made
this demo of them. If we assume these two are
good, then we must increase the size of the remaining keys to be
compliant with the visual size ratios between them in the “leaked”
photos. This update implements that change (luckily it seems it was still the 157% scale across the board). Several comparisons have been made between the tested and untested keys to make sure various features “line up,” however these have STILL NOT BEEN TESTED. The
attempt here is to at least get close to fixing something that was definitely wrong.

I submitted a pull request for these, but I want you two to review it and merge it if you agree.
