### ISSUE TITLE
Repo layout suggestion

### ISSUE THREAD

**Issue by jimklo** [Xyl2k/TSA-Travel-Sentry-master-keys#7]
I've been following this repo, wondering if it makes sense to use a Git-Flow style of repo branches to support merging and testing. I'm thinking out loud here, but think some organization is needed. I've done a lot of Github based OSS development, but never on an STL files so I think the problem is slightly different. If anyone has an alternative, please suggest in this issue - and maybe the maintainer will consider.

For those not familiar with Git-Flow, info here: http://nvie.com/posts/a-successful-git-branching-model/

Heres what I'm thinking:
- Master: contains full stable releases of all keys
- Develop: contains unstable releases of all keys
- Release/[key number]: contains stable version of specific keys for testing
- Feature/[key number]: contains unstable development versions of specific keys

Pull requests should happen on Feature/[key number] branches from which these would be alpha versions. Once there is some confidence of stability - merge with develop to make it beta.  Then as we think the keys are ready for release candidates, merge into release/[key number].  Once enough feedback has been submitted, the release keys can be merged and tagged on master.

Also STL's should be just STL's - for specific printing guidance for specific printers, I'd say use the Wiki features to document how to print a set.

**Comment by johnnyxmas** [comment]
My thoughts:

That looks incredibly confusing, and borders on demotivating. I also think it's a bit much when you're dealing with something that has a binary outcome: either it does or does not work. If it does not work, you can open an issue and state the problem. When we think we have a solution, we can just correct for it and update the STL, where users can repeat the cycle if necessary. This is a very, very small project. Just like Steven thought having multiple directories was too much, this looks to be even more confusing.  

As for printing tips, that is way outside of the scope of this project. 3D Printers are so individually unique and highly effected by environmental and material factors that the wiki would end up being full of every possible tweak and situation, rendering it pointless. This would be akin to providing someone with plans for a steering wheel for their car, and then having to give them tips on how to steer their specific car every time road conditions change. The steering wheel doesn't need to be changed to correct for these situations, so it's not our problem as the designer of steering wheels to address that. If they need to be taught how to drive in the rain in a 1997 Audi A4, they're on their own to get that sorted out. If they need to figure out how to print these STLs on their homemade printer on a humid, windy day outdoors, that's their problem, not the STLs.

**Comment by MS3FGX** [comment]
That level of granularity might not be necessary for something like this, but I do agree there should be a process in place for staging modifications that are under review. Many people are getting many different results, and until it is sorted out what does and does not work for the majority, making changes is just being overly rash.
