### ISSUE TITLE
Please make suggestions for what materials are suitable

### ISSUE THREAD

**Issue by kristovatlas** [Xyl2k/TSA-Travel-Sentry-master-keys#8]
I've tried contacting some local printers, and haven't been able to find one nearby who is confident that their printer will:
a) Achieve the desired resolution to print function key teeth
b) Use a material compatible with use as a key. Some materials will be too soft or brittle.

If folks could post printers/materials that have worked so far, that would be greatly appreciated. This info could be merged into the README.

**Comment by MS3FGX** [comment]
First, I'd be very cautious about spending money on getting the keys printed right now. They are in a state of flux, and best case we can only say that two of them _probably_ work (but even there we have some debate). 

That said, I think the printers were being overly cautious. Even low end printers should be able to replicate these designs, at least for most of the keys. The people who've tested them so far have largely been using consumer-level machines. If they can't print these designs, I would wonder why business they have offering printing services to begin with. 

As for material, well, there's a reason you don't usually see plastic keys...

I wouldn't recommend a printed key for long term use, but it will certainly work for awhile. Certainly long enough to experiment with. Unless you plan on using them daily, I don't see that it will be a problem. If you're worried about them wearing out, just get more made.

**Comment by ssa3512** [comment]
I would expect that standard ABS or PLA would be sufficient for these locks, as they require a very small amount of torque to actually turn the cylinder.

**Comment by johnnyxmas** [comment]
I feel like this isn't a bug regarding the files., and shouldn't be discussed here. Perhaps a 3D printing forum or Thingiverse or something.

**Comment by kristovatlas** [comment]
I guess you could call it a feature request: Provide additional information about what materials these files have been printed on and used successfully.

**Comment by johnnyxmas** [comment]
A)  MS3FGX is correct. Do not have these "professionally" made in any way unless you're doing it strictly for novelty; several of them definitely do not work, especially 006. 

B) The ones I was able to test work great printed in PLA at a .01 layer height, which means ABS would work even better, which subsequently means there is no issue with these files as far as FEASIBILITY of printing goes. That means any trouble you're having is in regards to your printer setup, and NOT the source files, thus this is not a discussion suited for this repo.

What you're asking is not a feature request. All feature & bug requests / issues mean modification of the original files needs to be done. If what you’re asking does not involve having to change the files, then it is not a discussion for Github. 

Sorry to be blunt, but these keys are getting global publicity, attracting tons of people, and we need to keep the repo as clean as possible. Thus, we need to eliminate scope creep at all costs. If there is not a problem SPECIFICALLY WITH THE FILES IN THIS REPO, please do not open up such requests.
