### ISSUE TITLE
002 Appears to need a groove on the other side

### ISSUE THREAD

**Issue by johnnyxmas** [Xyl2k/TSA-Travel-Sentry-master-keys#9]
[Per this tweet](https://twitter.com/RevitFur/status/643612939379830784)

This is congruent with the way I would expect the lock to be laid out.

**Comment by johnnyxmas** [comment]
0.75mm wide x 0.75mm deep with a 0.5mm ridge between the original cutout

**Comment by exibar** [comment]
002 for sure needs a groove on both sides...

**Comment by johnnyxmas** [comment]
![co6lf3luwaeuaav](https://cloud.githubusercontent.com/assets/6288329/9878739/d522b8f6-5b89-11e5-9092-04260d9074e6.jpg)

**Comment by johnnyxmas** [comment]
![co6z6t-ucaa3aev](https://cloud.githubusercontent.com/assets/6288329/9878743/db94e3c6-5b89-11e5-9d32-f6744c453bf8.png)

**Comment by MS3FGX** [comment]
I've been working on TSA002 a bit, and have come up with some improvements.

On my printer it works reliably, at least one side. I think I might be having some overhang issues on the other side, but I can't be sure. Hopefully some others can print it and see what kind of results they get. I'll make a PR for it soon.

**Comment by Gnagha** [comment]
The TSA002 worked. I also made a copy at a keymaker
![tsa002](https://cloud.githubusercontent.com/assets/14783930/10021687/6ffb8cf8-6149-11e5-867b-f34d95b29e67.jpg)

**Comment by johnnyxmas** [comment]
Excellent. If we can get a couple more confirmations, we can close this.

**Comment by Xyl2k** [comment]
very nice

**Comment by Xyl2k** [comment]
Received my tsa002, from latest MS3FGX update:

![2015-09-23_14-22-52](https://cloud.githubusercontent.com/assets/8536299/10044926/c433598a-61fe-11e5-853c-b76e5e94398f.jpg)

**Comment by johnnyxmas** [comment]
Looks solid. I’m willing to call this issue closed if you are.

**Comment by Xyl2k** [comment]
i think it's good yep

**Comment by MS3FGX** [comment]
Awesome, looks like another one down.
